---
title: "Introduktion till GeoServer"
author: "Gispo Sverige Ab"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "Introduktionskurs till GeoServer"
output:
    bookdown::html_book:
        toc: true
        theme: null
        template: custom.html
        css: custom.css
        split_by: chapter+number #rmd
documentclass: book
---

<!-- Harjoitukset -->

# INTRODUKTION TILL GEOSERVER

## Välkommen till GeoServerkursen!
Syftet med denna kurs är att vägleda dig i användningen av GeoServer. Erfarenhet av geografisk information eller andra GIS-programvaror är inte nödvändig för att delta i utbildningen. Naturligtvis är det till stor hjälp att ha sådan erfarenhet. Fråga gärna läraren om mer information om terminologin eller något annat är oklart.

## GeoServers bakgrund
GeoServer är en serverprogramvara byggd på öppen källkod som används för att dela, bearbeta och hantera geospatial data. GeoServer har funnits sedan 2001 genom projektet "The Open Planning Project". År 2014 blev GeoServer en del av OSGeo. GeoServer uppdateras var sjätte månad, och användarbasen är mycket livlig och aktiv.


## Instruktioner för övningssidorna

Kommandon som körs i **webbläsaren** ser ut så här:

::: note-box
<http://localhost:8080/geoserver>
:::

Kommandon som körs i en **terminal** ser ut så här **Komentorivillä**:

::: commandline-box
sudo lsb_release -a
:::

**Filers innehåll** ser ut så här:

::: file-content-box
#IPv4 local connections: #host all all 127.0.0.1/32 md5
:::

**HTML- och CSS-koder, SQL-kommandon samt Python-skript** ser ut så här:

::: code-box
SELECT version();
:::

**Frågor, extra information och tips** ser ut så här:

::: hint-box
Var hittar jag mer information om GeoServer?

GeoServer har egna webbsidor.

Psst! Du hittar information om GeoServer på internet.
:::

## Var hittar jag mer information?

Nedan ser du några sidor med mer information:

::: note-box
<https://geoserver.org/>
:::

::: note-box
<https://gis.stackexchange.com/>
:::

::: note-box
<https://www.osgeo.org/>
:::

## Fel

Om du upptäcker några fel i materialet, vänligen meddela kursledaren eller skicka ett e-postmeddelande till [info\@gispo.se](mailto:info@gispo.se){.email}.

## Licens och rättigheter
Dessa material har utvecklats av Gispo Sverige Ab för kursen "Introduktion till GeoServer". Materialet är licenserat med följande licens: [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)